# Generated by Django 3.0.7 on 2020-07-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodo', '0002_auto_20200718_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
