# Generated by Django 3.0.7 on 2020-07-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodo', '0003_auto_20200718_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='createdBy',
            new_name='user',
        ),
    ]
